### ISSUE TITLE
[question] new api key?

### ISSUE THREAD

**Issue by pirate486743186** [dglent/meteo-qt#100]
Ii'm using the api key from an other project...
https://github.com/fcambus/ansiweather

That's kind of naughty of me.
why you aren't making a new one?

personal api keys are creepy spying attempts.

**Comment by dglent** [comment]
Yes i can try again to provide a default key
What you mean with 'personal api keys are creepy spying attempts' ?

**Comment by pirate486743186** [comment]
it's so that they can sell your data to advertisers...
