### ISSUE TITLE
Fails to add any city

### ISSUE THREAD

**Issue by shiznix** [dglent/meteo-qt#101]
Hi,

Am trying this out for the first time and while it looks great from the screenshots I'm struggling to get it to work.
After adding my openweathermap API key (confirmed to be correct), the config prompts for me to add a city.
Unfortunately no matter what city I add, after clicking 'Apply' or 'OK' the program crashes and throws this error:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/meteo_qt/meteo_qt.py", line 1356, in config_save
    self.tray()
  File "/usr/lib64/python3.6/site-packages/meteo_qt/meteo_qt.py", line 1262, in tray
    if (self.temp_trend != '' or self.trendCities_dic[self.id_][1] ==
KeyError: ''
Aborted (core dumped)

**Comment by dglent** [comment]
Which version do you have ?

**Comment by shiznix** [comment]
Thanks for super quick response.

My apologies, I see now I was using an old version 0.9.9 :/
Have updated now to 1.8 and works great for current weather only.
It seems OpenWeather don't support weather forecast? :(

The systray icon is mangled because the temperature value is laid over the top of the weather icon. Would be great if there were a way to have the temp next to the icon, not a lot of vertical real estate in systray panel.

**Comment by dglent** [comment]
- Yes the forecast is displayed for the day (3 hours forecast) and for the next 4 days

- The tray icon cannot have dimensions bigger than a common icon (it is not like the Desktops widget where the width is larger than an icon). If i put the icon and the temperature horizontally there is not enough space. You can have only the T° or only the icon or toggle icon and T° every a defined time in seconds from the options.

- You can compare the received informations if you enable the DEBUG level in options and then run meteo-qt in a terminal. Open the links in the log to compare with openweathermap site : 

```
DEBUG: Fetching url for actual weather: http://api.openweathermap.org/data/2.5/weather?id=6457182&mode=xml&units=metric&APPID=xxxxxxxxxxxxxxxxxxx - 2590: meteo_qt
DEBUG: Fetching url for forecast of the day + 4: http://api.openweathermap.org/data/2.5/forecast?id=6457182&mode=xml&units=metric&APPID=xxxxxxxxxxxxxxxxxxxxxxxxxxxx - 2600: meteo_qt
```

I'm interesting to compare the values with the openWeatherMap site, i didn't find the Fells Like T° on the site. Do you have a specific case to compare ?

**Comment by shiznix** [comment]
Thanks for clarification wrt. systray icon.

This is what the log gives me...
ERROR: Url of 6 days forcast not available: http://api.openweathermap.org/data/2.5/forecast/daily?id=2078025&mode=xml&units=metric&APPID=a3bf6a5dff03d132af707bad9994aae1&cnt=7 - 2413: meteo_qt
ERROR: 6 days forcast not available: HTTP Error 401: Unauthorized - 2414: meteo_qt
INFO: Actual weather status for: Adelaide AU 14.1° Feels like 7.21 °C shower rain - 2164: meteo_qt
ERROR: Cannot find Ozone index - 2605: meteo_qt

So it only tries for a 6 day forecast and fails.
'Feels like' in this instance should be around 12 degrees C, not 7.21

**Comment by dglent** [comment]
The 6 days forecast fails since openweathermaps removed it from free accounts. Now there is a possibility to have it i will examine it later (via one call api).
But you still have the 4 days forecast for now. 
Why you say that the Feels like T° should be 12°C , where to compare it ?

**Comment by dglent** [comment]
To see all log message choose DEBUG as loggin level in settings

**Comment by shiznix** [comment]
Thanks, I'd already set logging level to DEBUG.

Where is the forecast supposed to be displayed? I don't have any forecast at all.

To compare 'Feels like' temp, see 'App temp' column at http://www.bom.gov.au/sa/observations/adelaide.shtml
or https://www.foreca.com/Australia/Adelaide

**Comment by dglent** [comment]
I think that in OpenWeatherMap data the Feels Like is correct and not in Foreca data. In Foreca the wind now is 6 km/h and the temperature is 11° and the Feels Like 11° 
But in this site https://www.eldersweather.com.au/local-forecast/sa/adelaide the Feels Like is the same with OpenWeatherMap (8°C now)

You will see the forecast at the bottom of the application window (see the screenshot here: https://github.com/dglent/meteo-qt/blob/master/README.md)

**Comment by shiznix** [comment]
Odd, OpenWeather is showing accurate 'Feels like' now - a few days ago it was wildly out, 12° degrees with a feels-like of 2° when all other sites were stating feels-like was 9°.

Will keep monitoring over the coming days/weeks.

My missing forecast problem I see now is due to the entire application window missing.
Is it supposed to show up when clicking on the systray icon? Mine only pops up the 'Settings' menu.

**Comment by dglent** [comment]
What is your distribution and Desktop Enviroment ? 
With right click on the icon do you see the entry 'Toggle' (for Ubuntu only : https://github.com/dglent/meteo-qt/blob/71ba63072a52def4d716c585f30000dd2dcff62e/meteo_qt/meteo_qt.py#L114). 
If yes, you can use it to show the window.
If not, could you see what is your desktop session name with the following command?
```bash
echo $DESKTOP_SESSION
```

**Comment by shiznix** [comment]
Great, it works now!
Changed 'ubuntu' to 'unity' which is my $DESKTOP_SESSION and it shows a 'Toggle Window' in the dropdown menu now.

Thanks again for all your help, will close this issue now :)
