### ISSUE TITLE
Tooltip in KDE not interpreting <br/> as break

### ISSUE THREAD

**Issue by rdh76** [dglent/meteo-qt#103]
Love the app.  Minor issue in KDE Plasma when hovering over icon in system tray the popup markups don't get interpreted and makes the popup less easy to read.

Example:
Hartford US 70<br/>Feels like 74<br/>Overcast clouds

instead of:
Hartford US 70
Feels like 74
Overcast clouds

Minor issue but wondering if there is a fix that I can implement to make the text more pleasing.

Thank you.

**Comment by dglent** [comment]
Hello
Thanks for reporting this iI will check it the next days
I will install KDE as i 'm not sure to have understood with the example (is the same with the "instead of")

**Comment by rdh76** [comment]
Sorry.  I see the problem in my written email.  The markups were interpreted so I will try to disguise them so you see how the tooltip looks.  Instead of "br" for break, I wll substitute "foo".

Hartford US 70<foo/>Feels like 74<foo/>Overcast clouds

or substituting [ for <
Hartford US 70[br>]Feels like 74[br>]Overcast clouds

so the break "br>" is not being properly interpreted in the tooltip.

Hope this is more clear.  I could not capture the tooltip in a screenshot.

Thank you.

**Comment by rdh76** [comment]
foo disappeared in my comment above.....interpreted and ignored as a markup.

**Comment by dglent** [comment]
It seems a KDE specific behaviour : https://bugs.kde.org/show_bug.cgi?id=422616, https://invent.kde.org/frameworks/plasma-framework/-/merge_requests/6

I will see if i can change something to cover also KDE tooltip specifications
I have Plasma 5.15.4 installed to test. I had another problem. If i run meteo-qt manualy everything is fine (The tootltip is in HTML formated.) But if meteo-qt is started with autorun i see the HTML tags instead as you. I will investigate better with a newer version

For now, could you try to use plain text in your installation ?

Change here
https://github.com/dglent/meteo-qt/blob/07d436a20d620e052f3f7c2500015df28b949719/meteo_qt/meteo_qt.py#L2260
and here
https://github.com/dglent/meteo-qt/blob/07d436a20d620e052f3f7c2500015df28b949719/meteo_qt/meteo_qt.py#L2269

the tags <br/> to \n

**Comment by rdh76** [comment]
Thank you.  I replace break tags with the new line \n indicator.  Tooltip looks good now.  I thank you for investigating this and providing a quick response and solution.
