### ISSUE TITLE
Infinite loading after initial installation

### ISSUE THREAD

**Issue by racuna** [dglent/meteo-qt#104]
Hi,

I just installed meteo-qt from the PCLinuxOS repository. After the initial configuration (api key, start on boot, metric system, and select some cities), the tray icon keep in a "loading" animation. If I launch meteo-qt from the command line I got this messages:

```
must be str, not NoneType - meteo_qt
WARNING: Error: must be str, not NoneType - meteo_qt
INFO: Try again...1 - meteo_qt
```

with the "try again" number increasing.

I'm using Python 3.6, if you need more info I'll be glad to provide it to you. 

Thank you very much.

regards,
Roberto

**Comment by dglent** [comment]
Hello

Which version did you install ?

**Comment by racuna** [comment]
Hi again,

meteo-qt-0.9.8

**Comment by racuna** [comment]
Oh, now I see. It's pretty old. I'll update from github instead. thanks

**Comment by dglent** [comment]
If you need an rpm, i think pclinuxos is compatible with mageia
http://mageia-gr.org/rpm/7/noarch/meteo-qt-2.1-1mgr7.noarch.rpm

**Comment by racuna** [comment]
Awesome, thanks
