### ISSUE TITLE
Meteo-Qt  bug on Ubuntu

### ISSUE THREAD

**Issue by Langjan** [dglent/meteo-qt#111]
My Meteo-Qt app on Ubuntu 20.04 Unity 64-bit shows a revolving circle that indicates it's trying to load, alternating with a square that appears to show "alerts." If I click there the normal drop down window shows up and I can access the settings. No error message shows except that the square appears to be an "alerts" link. There is also an "alerts" link that shows in the drop down menu but it's the only item that does not respond.

I have re-installed via Synaptic, then I tried to install via these instructions, same result: https://www.fossmint.com/meteo-qt-weather-app-for-linux/#comment-5307020860

**Comment by dglent** [comment]
Hello

thanks for the report
Could you send me the log file from ~/.config/meteo-qt/meteo-qt.log ?
Don't forget to hide your api key

**Comment by dglent** [comment]
I forgot to tell you to change the kog level to DEBUG from the settings dialog
Then when launching meteo-qt in the terminal you will see the error message
You can send me here the output _after hiding your personal api key_

**Comment by Langjan** [comment]
It keeps repeating debug efforts:
401 Unauthorized - 2111: meteo_qt
DEBUG: Trying to retrieve data... - 2086: meteo_qt
DEBUG: Download thread done - 2832: meteo_qt
DEBUG: Download thread done - 2832: meteo_qt
DEBUG: Download thread done - 2832: meteo_qt
DEBUG: Attempts: 3 - 2097: meteo_qt

Does this help?

[General]
APPID=
Autostart=True
CitiesTranslation={}
City=Bela-Bela
CityList=['Bela-Bela_ZA_941966']
Country=ZA
ID=941966
Proxy=False
StartMinimized=False
SystemIcons=ubuntu-mono-dark
Unit=metric
Wind_unit=df

[Logging]
Level=DEBUG

[MainWindow]
Geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0/\0\0\0\x18\0\0\x1\xd4\0\0\x1\x66\0\0\0/\0\0\0\x18\0\0\x1\xd4\0\0\x1\x66\0\0\0\0\0\0\0\0\x5\xa0\0\0\0/\0\0\0\x18\0\0\x1\xd4\0\0\x1\x66)
State=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\x1\xa6\0\0\x1O\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\0)

[SearchCity]
Geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0/\0\0\0\xa1\0\0\x3N\0\0\x1\xec\0\0\0/\0\0\0\xc1\0\0\x3N\0\0\x1\xec\0\0\0\0\0\0\0\0\x5\xa0\0\0\0/\0\0\0\xc1\0\0\x3N\0\0\x1\xec)

Jan Greeff
Tuintuiste 75, Posbus 3575, Bela Bela 0480
Tel. Jan 084 548 3890 Juanita 072 279 0298
Gesondheid sonder grense: https://verslank.net/
Jy verloor nooit deur lief te hê nie. Jy verloor altyd deur terug te hou.

**Comment by dglent** [comment]
It says "401 Unauthorized" 
Do you use a personal key or the default key ? 
Could you create/change your key ?

**Comment by Langjan** [comment]
The Openweather key in my laptop where the issue is being experienced, 
is the same as the one that is working in my desktop. I don't know 
whether it is a default or personal key. The only difference that I see 
in the settings is that in the laptop, there is, by "System tray icon" 
an additional setting for system default or many other different weather 
maps that does not appear in my desktop at all. Whatever I select here, 
including "Openweathermap" does not seem to make any difference.

There is a clickable link to "Create key" that takes me to the 
Openweather website. That site is a veritable nightmare to me and 
currently I cannot sign in, not even via their "lost password" effort.

**Comment by dglent** [comment]
Which version of meteo-qt do you use ?

**Comment by Langjan** [comment]
Both the problematic one on the laptop and the working one on the 
desktop are Python 3.8.5 - Qt 5.12.8 - PyQt 5.14.1 on Linux.

**Comment by dglent** [comment]
And the meteo-qt version is the same ?

**Comment by dglent** [comment]
Can you try this key ?
4f9ab1745f68f69eaab8fc1b894d6068

**Comment by Langjan** [comment]
Entered the key, then restarted Meteo-Qt and it's working perfectly. 
Many thanks. May I keep that key?

Jan Greeff
Tuintuiste 75, Posbus 3575, Bela Bela 0480
Tel. Jan 084 548 3890 Juanita 072 279 0298
Gesondheid sonder grense: https://verslank.net/
Jy verloor nooit deur lief te hê nie. Jy verloor altyd deur terug te hou.

**Comment by dglent** [comment]
Ok
Yes you can keep it as long as it works ;)
Thanks for reporting
