### ISSUE TITLE
Python Update

### ISSUE THREAD

**Issue by martynjy** [dglent/meteo-qt#112]
Since the latest Python update the hourly weather for the current day is missing and UV is stuck at 'Fetching...'.

**Comment by dglent** [comment]
Which version of Python ?

**Comment by dglent** [comment]
Can you try the version 2.3 ?

**Comment by martynjy** [comment]
Sorry, I should have been clearer.  The following were upgraded along with many other python libraries:

python 3.9.2-1
python-lxml 4.6.3-1
python-pyqt5 5.15.4-1
python-sip4 4.19.25-1
python-urllib3 1.26.4-1

I am using Arch Linux with 'meteo-qt 2.0.1-1' from the AUR.

**Comment by martynjy** [comment]
The current version in AUR is '2.0.1-1'.  It has not been updated since 2020-07-06.

**Comment by dglent** [comment]
So this is the problem. Could you ask please  to arch packagers to update meteo-qt to the latest release ?

Thanks
