### ISSUE TITLE
Font size minimum limit too high

### ISSUE THREAD

**Issue by chriswyatt** [dglent/meteo-qt#119]
After the recent X.org server update, my DPI is set correctly (it was wrongly set to 96 DPI before). This made everything become very chunky, so I had to reduce all my font sizes to compensate for this change. Meteo-qt enforces a minimum of 12 points (however, this can be reduced by modifying the config file directly). It would be nice if you could set this in configuration window too. Currently my font size is 9 points.

**Comment by dglent** [comment]
Thanks for inform about this.
I will redefine the minimum value to 6 in the configuration spinbox. It should be ok according your comment
