### ISSUE TITLE
Wishlist: % Chance of Precip

### ISSUE THREAD

**Issue by Linux-Geezer** [dglent/meteo-qt#120]
It would be nice to know the chance of precipitation both for the hourly forecast and the 4-day forecast.

**Comment by dglent** [comment]
Hmm, it is already [implemented](https://github.com/dglent/meteo-qt/releases/tag/v2.3) this but you use an old version ...

**Comment by Linux-Geezer** [comment]
Link says precip type changed to precip chance. Where? I'm not seeing it. No, I'm currently using my Arch install, which has the latest version.

[https://postimg.cc/jn4HK2qR](url)

**Comment by dglent** [comment]
You have this info in its tooltip. Precipitation probability
Here in the code:
https://github.com/dglent/meteo-qt/blob/3e8d6330e852fa52c719e88349f01ca9d9b08f83/meteo_qt/meteo_qt.py#L208

**Comment by dglent** [comment]
Which version do you have ? May be is an old one

**Comment by Linux-Geezer** [comment]
I'm using version 3.0-1 via the AUR. Tool tip shows _light rain_, _moderate rain_, etc., not the % chance; e.g. 20%, 50%, etc.

[https://postimg.cc/4Yg3VP12](url)

**Comment by Linux-Geezer** [comment]
Okay, the tool tip for the 4-day forecast shows the chance of precipitation. It would be nice to have the same for the hourly forecast.

**Comment by dglent** [comment]
Normaly is présent in the hourly forecast too.
Could you try with anorher city ?

**Comment by Linux-Geezer** [comment]
Okay, I see it now. You have to mouse over the hour text, not the icons. Thanks again for all of your help, your prompt responses, and your patience. It's a very nice app by the way.

I don't see a donation link. Are you not accepting donations towards development of the app?
