### ISSUE TITLE
Meteo-Qt no forecast

### ISSUE THREAD

**Issue by Langjan** [dglent/meteo-qt#125]
I have installed Meteo-Qt in my Ubuntu 20.04 Unity desktop, but the only windows that appear are the menu and the configuration settings. I have configured the settings to show my home town, but no weather details or forecast is shown.

**Comment by dglent** [comment]
I think is same with #126

**Comment by dglent** [comment]
Create a personal key from http://home.openweathermap.org/users/sign_up
