### ISSUE TITLE
meteo-qt forcast is not completing

### ISSUE THREAD

**Issue by SamBozman** [dglent/meteo-qt#126]
I am using Linux Mint. The program starts but only shows the current conditions. It shows that it is retrieving the UV conditions but never finishes. No future forecast is shown. It looks like open_weather_map has changed some of it's API's. Could this be the problem?

**Comment by dglent** [comment]
Which version do you use ?
install the latest version or create a personal api key.

**Comment by SamBozman** [comment]
This was my fault.
I missed this line in the instructions.
**In addition to the runtime dependencies stated above binariespylupdate5 of PyQt and lrelease of Qt Linguist are needed.**

My apologies. It works prefectly! 

Sam Bozman
