### ISSUE TITLE
Current Conditions Sometimes Way Off

### ISSUE THREAD

**Issue by Linux-Geezer** [dglent/meteo-qt#128]
In general, I love this app. It's the most eye appealing and informative weather app I think I've ever used. However, there is one complaint I have. The current conditions are sometimes way off. As I write this, the app is showing "overcast clouds" for the current conditions for my area. However, the sun is shining brightly. I've also had experiences where the app says it's raining when it's not and vice versa.

I also checked my location on the Open Weather Map site and it's wrong there as well, but says "broken clouds".

**Comment by dglent** [comment]
Hello, 

When i want to compare the server data with the application's displayed data, i run meteo-qt in the terminal with DEBUG logging level. Then open the url that match the wanted data (for example you will see messages like "forecast data for the day" or "for the next days" ... and then the url)
Then in the browser you can see if you have the displayed data in meteo-qt
If the data at server's side are not correct, you can report it to [openweathermap site ](https://home.openweathermap.org/questions)

and i'm glad for appraciating the application, unfortunately i don't have time now to take care more for the layout.
I worked in this application for learning and to have a system tray weather icon (in a DE without widget as LXQt) purposes.
If i'd started today, i would make many things in a different way; maybe one day i will have the possibility to rewrite it completely (or some parts...) ...

**Comment by dglent** [comment]
I close this issue, if you see that the received data are not the displaying data please reopen, or if you need some help to check this
