### ISSUE TITLE
Applet never finishes loading

### ISSUE THREAD

**Issue by finjulhich** [dglent/meteo-qt#131]
I've installed the last version 3.2

Debug logs look like this. Multiple download threads finish. 
**actual weather** succeeds
**Forecast +4 days** succeeds 
But **6 days** and **OneCall** fail.  as I've tried them manually.

I have a free subscription.  The point is after 2 minutes, the applet still doesn't show graphical data

`INFO: Try again...10 - 2818: meteo_qt
DEBUG: Fetching url for 6 days: http://api.openweathermap.org/data/2.5/forecast/daily?id=2643743&mode=xml&units=metric&APPID=xxxxxxxx&cnt=7 - 2670: meteo_qt
DEBUG: Url of 6 days forcast not available: http://api.openweathermap.org/data/2.5/forecast/daily?id=2643743&mode=xml&units=metric&APPID=xxxxxxxx&cnt=7 - 2694: meteo_qt
DEBUG: 6 days forcast not available: HTTP Error 401: Unauthorized - 2695: meteo_qt
DEBUG: Fetching url for actual weather: http://api.openweathermap.org/data/2.5/weather?id=2643743&mode=xml&units=metric&APPID=xxxxxxxx - 2698: meteo_qt
DEBUG: Fetching url for forecast of the day + 4: http://api.openweathermap.org/data/2.5/forecast?id=2643743&mode=xml&units=metric&APPID=xxxxxxxx - 2705: meteo_qt
DEBUG: OneCall URL: http://api.openweathermap.org/data/2.5/onecall?lat=51.5085&lon=-0.1257&exclude=current,minutely,hourly,daily&appid=xxxxxxxx - 2770: meteo_qt
ERROR: Error:
401 Unauthorized - 2811: meteo_qt`

Any ideas

**Comment by dglent** [comment]
The internal api key has been blocked, you need to create a personal openweathermap key. You will find in the settings the field to enter the key and the link to create one from the openweathermap.org website (for free)

**Comment by dglent** [comment]
Fix for onecall:
https://github.com/dglent/meteo-qt/commit/1b64e862ac9ba8adfd5d41aa4027a6da629ecb29
