### ISSUE TITLE
Transparency

### ISSUE THREAD

**Issue by ArchieA** [dglent/meteo-qt#133]
Hi.

First, thank you for the awesome widget. I have more of a question than an issue. Is there a way to make the background transparent or just completely remove it?

Thank you for your attention.  Thanks again.

**Comment by dglent** [comment]
Hello

nice idea

Could you add these lines :
self.setAttribute(Qt.WA_TranslucentBackground)  # transparent background
self.setWindowFlags(Qt.FramelessWindowHint)  # removes the window title bar

in the initialization of the widget here:
https://github.com/dglent/meteo-qt/blob/92ec15380a227fc28ddb0179ab51639cfcbdd4a6/meteo_qt/meteo_qt.py#L63
after the `super(SystemTrayIcon, self).__init__(parent)`
and test it ?


![εικόνα](https://user-images.githubusercontent.com/4337756/232276563-497971a5-cc88-4b86-b1e1-86653076c016.png)

**Comment by ArchieA** [comment]
Thank you, Ευγενικός Κύριος

It was easy enough. 

![meteo+conky](https://user-images.githubusercontent.com/1233718/232357824-d94a66d7-fe31-4ea6-995d-bfc427c7d6e7.png)
