### ISSUE TITLE
Arch Linux System Upgrade Breaks meteo-qt v3.3-1

### ISSUE THREAD

**Issue by Linux-Geezer** [dglent/meteo-qt#134]
After performing a system upgrade on Arch Linux, meteo-qt v3.3-1 fails to run. Attempting to run the app from the command line results in the following error:

`Traceback (most recent call last):
  File "/usr/bin/meteo-qt", line 4, in <module>
    from meteo_qt import meteo_qt
ModuleNotFoundError: No module named 'meteo_qt'`

There were a number of python packages that were upgraded, so I'm not sure which one(s) might be the culprit.

**Comment by dglent** [comment]
Hello

It is the same with this ?  
https://github.com/dglent/meteo-qt/issues/105

**Comment by Linux-Geezer** [comment]
Yes, same issue. I'll try the suggested solution and report back.

**Comment by Linux-Geezer** [comment]
> Hello
> 
> It is the same with this ? #105

The solution you provided in issue #105 resolved my issue. I learned something new about Arch Linux. Thank you.

**Comment by dglent** [comment]
Perfect
Thanks to @pmav99 :)
