### ISSUE TITLE
Add in README.md how to colaborate in translations

### ISSUE THREAD

**Issue by cpcbegin** [dglent/meteo-qt#140]
Add in README.md how to colaborate in translations

**Comment by dglent** [comment]
Thank you have right it is missing in the readme page
If you like you can send a PR with the modification (or i will do it a little bit later, i have to migrate also my local installation to transifex new api)

**Comment by rautamiekka** [comment]
I'd request LXQt if they would host the translation on their [Weblate](https://translate.lxqt-project.org), since they've said they don't mind it. Projects such as https://github.com/labwc/labwc are there, so it's worth the try.
