### ISSUE TITLE
Unable to add cities - 401 Unauthorized

### ISSUE THREAD

**Issue by annasmithforos** [dglent/meteo-qt#143]
Hi, I have the same problem as " Unable to add cities - 401 Unauthorized from API #132"

However I think I do have the latest version, is there another alternative. Thank you.

![Screenshot_20240409_125822](https://github.com/dglent/meteo-qt/assets/127437263/66a5529c-450d-4964-9c32-39e08fa84b79)
![Screenshot_20240409_131633](https://github.com/dglent/meteo-qt/assets/127437263/a5be6f4e-f1d0-4bf0-8b36-54ed6676ffdf)
![Screenshot_20240409_131311](https://github.com/dglent/meteo-qt/assets/127437263/f0f5be9d-6242-4901-b2ee-53b0742511e0)

**Comment by dglent** [comment]
Hello

You must install the latest version v3.3
https://github.com/dglent/meteo-qt/releases

**Comment by annasmithforos** [comment]
I'm sorry, I'm a bit embarrassed but I'm really lost, do I have to have the previous version installed first? I uninstalled it to start from scratch. I guess there is no .deb package (for beginners like me it is easier). If you confirm me that I have to have already installed meteo Qt I will try to upgrade with the zip or tar archives, but the latter will be more difficult for me.

Thanks for your patience.

**Comment by dglent** [comment]
You are not obliged to have a deb package
You can download the tar.gz https://github.com/dglent/meteo-qt/archive/refs/tags/v3.3.tar.gz
unzip it and run python meteo_qt.py in a terminal inside the folder "meteo-qt-3.3/meteo_qt"

**Comment by annasmithforos** [comment]
Thanks you very much! It rules.
Best regards.

**Comment by dglent** [comment]
👍
I suggest also to use a personal key from openweathermap.org (if it is not the case)
