### ISSUE TITLE
OpenWeather One Call API 2.5 to be closed

### ISSUE THREAD

**Issue by seemoss** [dglent/meteo-qt#145]
I just received the following email from OpenWeather (more info at https://openweathermap.org/api/one-call-api):

"It’s time to switch from One Call 2.5 to One Call 3.0! - One Call API 2.5 to be closed

Dear OpenWeather user,

We would like to inform you about our plans to complete the migration from One Call 2.5 to One Call 3.0 that started 2 years ago. In line with this, access to One Call 2.5 will be finally closed in June 2024.

One Call 3.0 provides you with significantly advanced business-demanded features such as a minute forecast for 1 hour, 4 days forecast for any timestamp, a daily forecast for 8 days, including a human-readable summary, historical data (45-year archive) for timestamps, and with daily aggregation, 1.5-year long-term forecast with daily aggregation, and others.
Click here for One Call 3.0 migration guide (https://openweathermap.org/one-call-transfer) [etc.]"

Will this affect meteo-qt, or does it already use API v3?

Is there any action for meteo-qt users to take? I assume that my existing API key will still work?

**Comment by dglent** [comment]
There is a call to One Call API 2.5 in meteo-qt to receive National Weather Alerts.
But this is not free any more, so we don't receive the weather Alerts now (but the call is still in use)

So after the évolution of this API meteo-qt will still work.
Except if someone use a paid API key which i don't think that someone does (but who knows...)

Thanks for informing for this.
