### ISSUE TITLE
Doesn't use system Qt theme on NixOS

### ISSUE THREAD

**Issue by linuxissuper** [dglent/meteo-qt#171]
I've built meteo-qt for nixos but unfortunately it uses the default Qt theme  
that's my theme:  
![image](https://github.com/user-attachments/assets/9b61bebc-c5e8-4049-8151-0da4281e3a1b)
vs  
![image](https://github.com/user-attachments/assets/debd06e8-7e9c-4889-a65d-e178d499b538)
  
I've also installed meteo-qt via arch linux in distrobox and it is also uses the default Qt theme 
  
Any idea what I'm missing?

**Comment by dglent** [comment]
I think that you have to configure qt style with https://sourceforge.net/projects/qt5ct/
Maybe will work also if in the lxqt settings you choose qt5ct Qt Style in your screenshot (if qt5ct is installed)
Here https://github.com/dglent/meteo-qt/issues/75 the configuration is done with qt5ct

**Comment by linuxissuper** [comment]
it seems qt5ct also doesn't work
  
`unset QT_STYLE_OVERRIDE; QT_QPA_PLATFORMTHEME=qt5ct qt5ct`:
![image](https://github.com/user-attachments/assets/9517d895-df96-4c86-a6d1-87ae3896aa4d)
  
`unset QT_STYLE_OVERRIDE; QT_QPA_PLATFORMTHEME=qt5ct meteo-qt`:
![image](https://github.com/user-attachments/assets/ad17075f-691a-41f2-8581-4dd2918025de)

Just to have it mentioned: all Qt apps on my system use the right theme except meteo-qt  
not sure if this is ja nixos thing oder pyqt or both

**Comment by dglent** [comment]
I tried on my system (i use Mageia 9 and LXQt 1.4.0) and when i change the style it changes also in meteo-qt
Could you reproduce it with other pyqt applications ?

![Peek 2024-11-27 05-25](https://github.com/user-attachments/assets/862a9072-ba05-4f5f-a85e-b1fa65a10f7b)

**Comment by linuxissuper** [comment]
I've tested `opcua-client-gui` and it works  
![image](https://github.com/user-attachments/assets/21f61ae0-af86-44b4-89ea-940d0b87d877)
  
I think it's a nixos thing but I don't see how `opcua-client-gui` is different

**Comment by dglent** [comment]
And if you try by running meteo-qt by sources directly ? May be you have already done. What you expect is to change the Grey color of the weather panel ? What about the buttons in meteo-qt settings ?

**Comment by linuxissuper** [comment]
> And if you try by running meteo-qt by sources directly ? May be you have already done. What you expect is to change the Grey color of the weather panel ? What about the buttons in meteo-qt settings ?

can't get it to run 
```
QFactoryLoader::QFactoryLoader() checking directory path "/nix/store/7x6mf0h4z743nrdvszj5xc4l1ig4nif6-python3-3.12.6/bin/platforms" ...
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

zsh: IOT instruction (core dumped)  QT_DEBUG_PLUGINS=1 python3 meteo_qt/meteo_qt.py
```

The settings are also using the default Qt theme
and yes, I'd expect grey color and same widget style

**Comment by linuxissuper** [comment]
> Ha! I can reproduce it when i run meteo-qt from the source (python meteo_qt.py). The change of the theme has no effect but the window has always the default used theme of the system when i logged in in the session. Normal usage with the rpm package works ok

hm, unfortunately the nixpkg doesn't use the widget style nor the color  
I think something's missing for the nixpkg, some Qt env variable or something

**Comment by dglent** [comment]
When i add this line
_def main():
    app = QApplication(sys.argv)_
    print(app.style().objectName())

it prints "qt5ct-style"

When i run from source file i have to use the tool qt5ct to change the theme and have effect in meteo-qt
Otherwise, to use the settings from lxqt i have to run from the executable from here: https://github.com/dglent/meteo-qt/blob/master/bin/meteo-qt 

But in any case this is not handled from meteo-qt, the same for the icons theme, it gets the theme from Qt library which is set from the system (qt5ct or lxqt controle center)

**Comment by linuxissuper** [comment]
today I've updated nixos to `24.11` and now it works! 🎉  🥳
![image](https://github.com/user-attachments/assets/ebde6237-0238-4ffc-8170-358aae8da036)
  
I don't know why 🙈  
but oh well :)
