### ISSUE TITLE
Error 110: connection timeout

### ISSUE THREAD

**Issue by urbanomad64** [dglent/meteo-qt#36]
I have been getting various connection errors recently. I believe it is since the update from 0.4.3 to 0.5.0...

**Comment by dglent** [comment]
Hi, i have the same problem today but not only in meteo-qt but also when i search a city in openweathermap.org
You can try if it works the website, in my case it doesn't work.
It seems that is a temporary problem of their server

Sean Sloane <notifications@github.com> a écrit :

**Comment by dglent** [comment]
See here:
https://twitter.com/OpenWeatherMap/status/576810346159063040

**Comment by dglent** [comment]
For me it works again now, is it the case for you too?

**Comment by dglent** [comment]
I dont have any problem since the 15 Mars
If you occur the problem please reopen the issue, thanks for reporting.
