### ISSUE TITLE
Move translations to a GMS platform (e.g. Transifex)

### ISSUE THREAD

**Issue by skybon** [dglent/meteo-qt#37]
Forcing volunteers to study Qt Linguist and open Pull Requests for every edit of translation is just not cool. Also updating .ts files after every single template change is pain.

A platform like Transifex or Launchpad will help with crowdsourcing translations from concerned citizens without technical skills. Maintaining existing ones will become easier too.

**Comment by dglent** [comment]
Hi, i agree and i think also that transifex would be a good choice.

**Comment by skybon** [comment]
You can use Mumble Transifex bot for pulling translations to GitHub.
https://github.com/mumble-voip/MumbleTransifexBot

**Comment by dglent** [comment]
Ok the transifex support is enabled, files available to translate are here:
https://www.transifex.com/projects/p/meteo-qt/

Thanks for the suggestion (i will take a look also to the Mumble i didn't see yet)
