### ISSUE TITLE
Update English template, remove .qm files

### ISSUE THREAD

**Issue by skybon** [dglent/meteo-qt#38]
Several strings in the current English template are out of date. Also consider removing compiled translation files from repository and setting up Transifex auto-update from https://raw.githubusercontent.com/dglent/meteo-qt/master/meteo_qt/translations/meteo-qt_en.ts.

**Comment by dglent** [comment]
-I think i didn't understand the flow between git and transifex
As i do some modifications for the next version i didn't update the translations file yet. I counted to do it once i have done and then push the new translations in transifex.
Is it ok ?

- I defined the above url for the resource automatic update in transifex

- I thought that the qm files could serve in case that you download the archive and run the program directly without install it by the setup.py... but i 've just realized that also others in git don't keep these files, so i deleted them ...

Thanks
