### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by ozky** [dglent/meteo-qt#41]
Can you add feature to change panel icon font size is very unreadable small ?.

**Comment by dglent** [comment]
Hi okzy, ok, i will take a look, maybe also to have the option to have only the temperture ...
Which desktop you use? for example in lxqt i think that the size of the weather icon and the size of the font have an optimized size in the same icon:
https://lut.im/G1oyiox4/eSGy4Lr9

**Comment by dglent** [comment]
Hello, you can test this:
https://github.com/dglent/meteo-qt/commit/8540e9a27416866303a032ebd82d54edbb161831

it has a range of 12 - 25 for the font size.
Maybe is usefull to add an option to hide the weather icon and show only the T° (?)

**Comment by AndydeCleyre** [comment]
I'm finding the max size of 32 to be still too small:

![image](https://user-images.githubusercontent.com/1787385/54623964-deeece00-4a42-11e9-9406-84c7fc21d008.png)

**Comment by dglent** [comment]
Font dialog to set the font of the T° in the system tray https://github.com/dglent/meteo-qt/commit/5d528e2f40c1ad5550b405a81a0d309a9f84b90e
