### ISSUE TITLE
alignment of objects displayed by meteo-qt

### ISSUE THREAD

**Issue by pmattern** [dglent/meteo-qt#45]
If meteo-qt is configured to display both icon and temperature the horizontal alignment within the area that's at meteo-qt's disposal isn't centrally any longer but left, compare display of both icon and temperature
![meteo-qt_horizontal-alignment_icon temperature](https://cloud.githubusercontent.com/assets/9860801/11575573/1867141a-9a12-11e5-91ef-1bdb1dab5233.png)
with temperature
![meteo-qt_horizontal-alignment_temperature](https://cloud.githubusercontent.com/assets/9860801/11575577/1cc72dc4-9a12-11e5-814d-63b9ad76621e.png)
and icon
![meteo-qt_horizontal-alignment_icon](https://cloud.githubusercontent.com/assets/9860801/11575578/21002a9e-9a12-11e5-8360-8d73e964e028.png)
only respectively.

This for sure isn't a bummer, yet I think the UI would be more smooth if this got fixed, in particular as central alignment seems to be the default behaviour of virtually all similar applications.
Behaviour doesn't seem to depend on the technology used by the panel as it's the same in plugins "System Tray" of KDE Plasma 5 and plugin-statusnotifier of LXQt which are implementing SNI as well as in plugin-tray of LXQt and "Notification Area" of Xfce both of which are implementing the old System Tray Protocol.

Seen running 5bd50c0 on Arch Linux i686 or x86_64.

**Comment by dglent** [comment]
You have right, thanks for the screenshot, as i can discern better the alignment issue.
Could you test the above commit ?

**Comment by pmattern** [comment]
In aa750ce horizontal alignment seems to be centrally.
Finding at first glance, so maybe something more will come up in the long run. But for now this issue is apparently fixed.

Now that the horizontal alignment is fixed I stumbled upon something different: maybe the usage of vertical space at meto-qt's disposal should be improved, too.
E. g. in this screenshot
![meteo-qt_vertical-alignment](https://cloud.githubusercontent.com/assets/9860801/11625665/ea73bc0c-9cdc-11e5-8e4e-5966e699aef2.png)
icon and temperature kind of stick together while compared to this there's plenty of space below temperature and particularly above the icon.
So maybe the available vertical space could be divided into two halves with the vertical alignment of both icon and temperature being centrally within its respective half or so?

**Comment by dglent** [comment]
You have right, the icon was reduced and placed at the center.
Could you test the above commit please ?

**Comment by dglent** [comment]
Fixed in 0.8.8

**Comment by pmattern** [comment]
Regarding vertical placement the actual drawback wasn't the inefficient use of vertical space but the fact that icon and text (temperature) sort of stick together. And this can still be seen as of cac67d2.
I still think the UI would be more smooth and easier to read if the vertical space available got divided into two parts with both icon and temperature placed centrally in its respective half as depicted in my previous post. Would this eventually be doable and make sense?

**Comment by dglent** [comment]
In this screenshot the left icon is the old version and the right icon is the new (0.8.8)
![tray](https://cloud.githubusercontent.com/assets/4337756/11915452/01317dde-a6a7-11e5-8112-f787cfde372a.png)

I don't think that now remains any vertical space available (comparing with the icons beside)

**Comment by pmattern** [comment]
Sure. Depending on height of panel, font size and so on sometimes there just isn't any space left so any attempt to further improve the placement is pointless.
The suggestion above was meant to make use of vertical space more reasonably and in particular to get a bit more distance between icon and text in case some additional space is left only.

**Comment by dglent** [comment]
The icon uses the same place at the top. The temperature uses the place at the bottom according the chosen font size from the settings. The icon is not reduced, and this is wanted in order to be the maximu visible possible in the tray icon. If you increase the temperature font with the maximum value, will cover the icon.
What you wanted is to separate the tray icon in two parts and any change of the font size won't take place of the upper half ?
In this case you will loose the posibility to have the temperature a little bigger if you prefer, and the icon should be reduced. 
What i'm thinking about is to add an option to customize the size/position of the weather icon, so it can be defined according the favours.

**Comment by pmattern** [comment]
What I was actually having in mind is something like this

![meteo-qt_vertical-alignment](https://cloud.githubusercontent.com/assets/9860801/11957621/1278732c-a8c3-11e5-966b-9018b91ce10b.png)

But you're right. This would prevent setting icon to a particular large size at the expense of the text (temparature) size and the other way around.
So no clue what's the best thing to do or whether something should still be done in the first place. I mean it's just a minor usability issue anyway and it's not that meteo-qt would be looking awful right now.

**Comment by pmattern** [comment]
While the alignment in the tray icon probably doesn't really need any additional changes I stumbled upon a related finding in the main window:

The vertical alignment of headers in the left column seems to be central making them misplaced if the content at the right is expanding to more than one line.
Problem can be seen in this screenshot
![meteo-qt_main-window-horizonal-alignment](https://cloud.githubusercontent.com/assets/9860801/14817106/1e4f6958-0bb5-11e6-8589-49f525d93e13.png)
where header "Wind" at the left is between the two lines needed by text "Nordwest [...] Briese" at the right.

**Comment by dglent** [comment]
This happens also with the UV, because the description has two lines the title is positioned in the middle automatically by qt. You think that it should be aligned to the top (or the bottom) of its cell ?

**Comment by pmattern** [comment]
It's true, UV is affected as well.

Personally I think the vertical alignment of what I called "header" above should definitely be at the top, not at the bottom of the cells.

On a side note I'm not sure whether the values of parameters "Wind", "Cloudiness" and so on should get a bit more horizontal space at their disposal.
Even when the window's horizontal size is rather large only a fraction is used.
![meteo-qt_horizontal-space-wind-etc](https://cloud.githubusercontent.com/assets/9860801/14830721/5e319c7a-0bf2-11e6-9d4c-4f9fc9b6b466.png)

**Comment by dglent** [comment]
In this commit the wind and uv headers are aligned at the top and the wind icon at the left
https://github.com/dglent/meteo-qt/commit/5edd8b94b0629bb00dfc73164967e56fc1befbfe#diff-9e48cad1514cd39ac5d1b29e0db965ce

**Comment by pmattern** [comment]
The alignment introduced in 5edd8b9 makes a lot of sense, IMO.

There's one other related detail I stumbled upon, though. Those colored rectangles representing the value of UV index and ozone are placed below the text as for UV but next to the text as for ozone.
![meteo-qt_placment-icons-uv-vs-ozone](https://cloud.githubusercontent.com/assets/9860801/15074112/802a74ca-139d-11e6-8b13-b1fb5e61bb48.png)
I think this should be consistent, possibly with current handling of icon "wind" as well meaning right of the text. Maybe it would even look good if the horizontal alignment of all three icons wind, UV and ozone was the same, that is all three icons are below each other in the respective row of some kind of column.

On a side note I'm getting no values for UV and/or ozone on a regular basis since some days. Connected by Deutsche Telekom, fwiw. Any idea what could be the reason here?

**Comment by dglent** [comment]
Font dialog to set the font of the T° in the system tray https://github.com/dglent/meteo-qt/commit/5d528e2f40c1ad5550b405a81a0d309a9f84b90e
