### ISSUE TITLE
urllib vs requests and proxy usage

### ISSUE THREAD

**Issue by codeshard** [dglent/meteo-qt#46]
Hello dglent!
Is well known that [request](http://docs.python-requests.org/en/latest/) library is more efficient and readable than [urllib.request](https://docs.python.org/3.0/library/urllib.request.html) library. [request](http://docs.python-requests.org/en/latest/)  provides a more pythonic way to process web responses and error handling, and also, provides a really nice layer of abstraction, making the code beautiful and easy to read and maintain. Have you consider use it?
In other hand, many people have corporative proxies(with or without authentication) to browse the web. Is there a chance to add the proxy option to [meteo-qt](https://github.com/dglent/meteo-qt)?

**Comment by dglent** [comment]
Hi! 
I used the urllib.request as it was the built in module, i didn't try the request yet.
I will add the proxy option both 'with' and 'without' authentication

Thanks for the suggestion
