### ISSUE TITLE
Autostart: additional instance per session in KDE Plasma 5 and Xfce

### ISSUE THREAD

**Issue by pmattern** [dglent/meteo-qt#48]
If meteo-qt gets launched by `~/.config/autostart/meteo-qt.desktop` as usual an additional instance gets added per session both in panel plugin (widget) "System Tray" of KDE Plasma 5
![multiple-systray_kde-meteo-qt](https://cloud.githubusercontent.com/assets/9860801/12158553/4935a14a-b4db-11e5-868c-843a5228d3ab.png)
and "Notification Area" of Xfce 4.12.
I didn't understand the exact technical details so far and hence cannot say whether meteo-qt or the panel plugins are to blame here. So I'll just state what I'd consider a relevant finding or thought.

The same behaviour can be seen with [LXQt ConnMan Applet](https://github.com/surlykke/lxqt-connman-applet) but neither with NetworkManager's nm-applet nor with the notifier of [Octopi](https://github.com/aarnt/octopi), a package management GUI for Arch Linux, all of which are started according to the Autostart Specification, too.
Problem can not be seen in LXDE or LXQt at all.

It doesn't seem to matter whether or not the application ("applet") that's meant to run in the panel plugin allows for running several instances in parallel. Octopi notifier doesn't but nm-applet as well as meteo-qt do.
nm-applet on the other hand throws a warning about a registered D-Bus object when a second instance is launched from a terminal emulator which could very well be related to the problem, IMO. Maybe the affected panel plugins are relying on D-Bus to check the status of the applets but don't get this information handed by the latter.

AFAIK only a single instance of a panel plugin implementing either the old System Tray Protocol or the new [K]SNI can be run at a time. If so it could eventually be considered a bug per se if applets allow for running several instances in parallel.
On the other hand panel plugins should not rely on some particular technology like D-Bus as assumed above to prevent several instances as long as this technology isn't a recognized standard.

**Comment by dglent** [comment]
In KDE we have seen that if it is in the shown applications in the tray, it doesn't run a second instance. If it is in the hidden apps, it runs a second instance.
I didn't try yet in xfce, i confirm also the expected functioning also in LXDE

As solution would be:
- Don't check the Autostart when running a DE where there are multiple instances (may be adding a tooltip information)
- Option for autostart available only in the working DEs this supposing that i have to test regularly the behaviour on every DE, and with the risk to recognized a wrong DE and disable the option wrongly.

I prefer the first

**Comment by dglent** [comment]
Should be tested in a newer Plasma installation
