### ISSUE TITLE
log files should be placed in $XDG_DATA_HOME

### ISSUE THREAD

**Issue by pmattern** [dglent/meteo-qt#49]
According to both the [specification](http://www.freedesktop.org/wiki/Specifications/basedir-spec) and the habits of many other applications user-specific log files should be placed in $XDG_DATA_HOME instead of $XDG_CONFIG_HOME, probably best at a path like `~/.local/share/meteo-qt/meteo-qt.log`.

**Comment by ozky** [comment]
This would be good idea but as meteo-qt have only two files inside settings folder,i see no point to use two folders with one file inside both folders.

**Comment by dglent** [comment]
Hello, 
On the one hand is good to keep the standards, on the other hand maybe is worst as Otto says 
Actually, i am in movement period, i will see this better later but tell me also your suggestions 

Thanks 

-- 

Dimitrios Glentadakis

**Comment by pmattern** [comment]
The idea is that looking for certain kinds of files should be intuitive.
If a problem comes up, it's just convenient to know where to look for the logs. If on the other hand applications make exceptions / implement own concepts things get more complicated as it's hardly possible to memorize many exceptions of different programs.
Of course it may look strange to create two directories each comprising a single file only. But creating a directory isn't a big deal and all in all I still think the advantages would outweigh any eventual disadvantages.

On a side note in the meantime I realized that some software like Openbox place their log files in $XDG_CACHE_HOME but I don't think that this makes really sense either.

**Comment by dglent** [comment]
The standard:
_"$XDG_CACHE_HOME defines the base directory relative to which user specific non-essential data files should be stored. If $XDG_CACHE_HOME is either not set or empty, a default equal to $HOME/.cache should be used."_
On my system the $XDG_CACHE_HOME is not defined
According this:
_"$XDG_CACHE_HOME defines the base directory relative to which user specific non-essential data files should be stored. If $XDG_CACHE_HOME is either not set or empty, a default equal to $HOME/.cache should be used."_
i looked in the ~/.cache directory, and i found only two log files: Openbox and Simplescan.
All other log files in home directory at situated in the config or the ~/.APPDIR/ or in ~/.local/share/data

I am a little confused, ok a log file contains non essential data, but maybe not ?
For example, you can delete the cache files of a database regularly but is the same for a log file ?

**Comment by pmattern** [comment]
I agree definitions and common practice aren't exactly concise. Comparing with the system-wide directories in `/` a real counterpart to `/var/log` doesn't exist at all. But considering `$XDG_CACHE_HOME` and `$XDG_DATA_HOME/applications` I'd tend to say the latter is more suitable.
Would actually be writing to systemd journal an option, too?

**Comment by juancarlospaco** [comment]
https://github.com/juancarlospaco/anglerfish#make_logger
A Logger, that has Colored output, logs to STDOUT, logs to Rotating File, it will try to Log to Unix SysLog Server if any, log file is based on App name, if the App ends correctly it will automatically ZIP compress the old unused rotated logs.

**Comment by dglent** [comment]
it seems convenant to have the log and the configuration file at the same place
