### ISSUE TITLE
Please use annotated tags

### ISSUE THREAD

**Issue by pmattern** [dglent/meteo-qt#55]
The tags currently used are the so-called lightweight ones. These don't get considered by `git describe` yielding results like this one
```
$ git describe --always 
v0.8.1-116-g8310605
```
from current master which doesn't really make sense.

The problem can be circumvented easily by using simple annotated tags. These can be set by running
```
$ git tag -a <name of tag> [-m <description>]
```
where omitting the description at the command line will open an editor to add it which is optional. Set that way they can get uploaded to GitHub by running
```
$ git push --tags <remote name>
```
and will then display in the output of `git describe`.

**Comment by dglent** [comment]
I applied the above and normally should be ok now with the next 0.9.3 version (i wait your confirmation for this issue before release it)

**Comment by pmattern** [comment]
All good in a local clone here, both in current master
```
$ git describe 
v0.9.3
```
and after adding a dummy commit in a test branch
```
$ git describe 
v0.9.3-1-g73f5b71
```

**Comment by dglent** [comment]
ok thanks, i will do as this from now
