### ISSUE TITLE
 Can't update weather information

### ISSUE THREAD

**Issue by Viterzgir** [dglent/meteo-qt#57]
ERROR: Error: 401 Unauthorized

**Comment by dglent** [comment]
I cannot reproduce it, which version do you have ?
Can you upload here the output in the teminal ?
Do you use proxy ?

**Comment by dglent** [comment]
I have this issue too

**Comment by dglent** [comment]
The problem is the over usage of the free api
Either the application has "too much" users, either the key is used too many times ...

I try to find out what happen in this cases and what could be the solution

**Comment by KaMiila** [comment]
This is also not working for me across multiple machines on different distributions and architectures.  armv7h (arch linux), x86_64 (slackware), x86_64 (virtualbox arch linux).

**Comment by dglent** [comment]
I'm about to write the option to add a personal key in case that the common key has over usage. I hope to have the update this week.
* The key that is in usage has been reseted so it doesn't work any more.

**Comment by pmattern** [comment]
In 6e00e39 there's a regression similar to #50, that is reproducible crashes and core dumps on new user profiles.
To reproduce make sure meteo-qt isn't running, remove `~/.config/meteo-qt/` if it preexists and launch meteo-qt. Open the settings dialogue and copy an OpenWeatherMap key. Hitting `Apply` and `OK` will make meteo-qt crash then.

On a side note the usage of an own OpenWeatherMap key had replaced the `401` error with a `500` HTTP error only here so far. (I cannot test the behaviour right now due to the problem stated above as I don't have a working profile at hand right now.)

**Comment by dglent** [comment]
@pmattern You have right, i didn't handle the first usage where you cannot find a city if you don't have a key
Thanks for seeing it.

*For info: the report of the dysfunction:
https://openweathermap.desk.com/customer/en/portal/questions/16336038-my-application-stopped-worked-because-of-over-usage

**Comment by dglent** [comment]
For the HTTP 500 error the guilty is the xml format which is used in meteo-qt:
https://openweathermap.desk.com/customer/en/portal/questions/16343680-internal-server-error

I will wait a little to see what they will do finally before rewrite things ...

**Comment by tigerjack** [comment]
I have the same problem here. I'm using the AUR package `meteo-qt 0.9.5-1` and the terminal continue to print the lines below

    qt5ct: using qt5ct plugin
    qt5ct: D-Bus system tray: no
    WARNING: Error: HTTP Error 401: Unauthorized - meteo_qt
    INFO: Try again...1 - meteo_qt
    # 10 times, then ...#
    CRITICAL: Cannot paint icon! - meteo_qt`

**Comment by dglent** [comment]
@tigerjack Please update to the 0.9.7 version
This has reduced the forecast to 4 days since the previous option became paid
https://openweathermap.desk.com/customer/portal/questions/17097710-4-1-error-when-invoking-forecast-api

**Comment by tigerjack** [comment]
Thanks @dglent . Is there a chance to see the new version in the AUR any time soon? Or the update from git is the only solution?

**Comment by dglent** [comment]
No you have to update the package with the latest version 
Maybe @pmattern could help you for the update
