### ISSUE TITLE
Weather status window too tall, forecast hidden underneath bottom panel

### ISSUE THREAD

**Issue by rdh76** [dglent/meteo-qt#59]
Is there a way to adjust the height of the weather status window?  Both in LXDE and LXQT, the window is sized to spill underneath the bottom panel so the forecast is obscured.  Is there a configuration file or other action where I can adjust this behavior so that the window fits from the top of screen to the top edge of the bottom task launcher panel.  Thank you.

**Comment by rdh76** [comment]
Never mind. I resolved the issue by changing the default font & font size.  Entire weather status window now visible.

**Comment by dglent** [comment]
Hello, glad to hear that works for you.
By the way, i didn't understand why you couldn't adjust (resize) the window ?
Do you have any specific device ? a very small screen ?
