### ISSUE TITLE
Crash due to exiting meteo-qt right upon first launch

### ISSUE THREAD

**Issue by pmattern** [dglent/meteo-qt#65]
Under certain conditions recent meteo-qt is crashing and dumping core when it is terminated from its context menu right after launching the first time on a new user profile.

Steps to reproduce
1. Make sure meteo-qt isn't running and `$XDG_CONFIG_HOME/meteo-qt` doesn't preexist. Launch meteo-qt and confirm the desktop notification informing that no city has been configured yet.
1. Leave meteo-qt by choosing "Exit" from its context menu (right-click on panel icon).

The crashes seem to be tied to certain conditions, most likely to meteo-qt being run in non-Qt panels. At least the problem doesn't exist in LXQt sessions here but does under Xfce or when lxpanel, the panel of LXDE, is running in an Openbox "only" (no desktop environment) session.
They can no longer be triggered when meteo-qt is quit the first time it's running without provoking the crash as depicted in the steps to reproduce, e. g. by adjusting some settings or so before hitting "Exit".

c78082b on Arch Linux. No helpful output when launching meteo-qt from a terminal emulator, traces can be found in [this GIST](https://gist.github.com/pmattern/9423dd30c490a8cf129b117d20163dee).

**Comment by dglent** [comment]
I couldn't find out the cause for this crash. 
I consider it as a minimal issue as there is only one case usage, exiting the program without configure any city (so without any usage)
