### ISSUE TITLE
Settings: dialogues to configure cities shouldn't both be called "meteo-qt"

### ISSUE THREAD

**Issue by pmattern** [dglent/meteo-qt#67]
Right now both the dialogue which opens upon clicking the wrench right of the form "City" in dialogue "Meteo-qt Configuration" and the dialogue to add additional cities which opens upon clicking "Add" in the former are named "meteo-qt". This is pretty inconvenient at times, and be it with regards to referring to those dialogues in bug reports only, see the somewhat awkward results from trying to be precise in #66.
So I think it would make some sense to rename the dialogues.
Not really sure about optional titles, but I guess just "Cities" for the former and "Add a city" for the latter would be at least an improvement for the time being.

**Comment by dglent** [comment]
Thanks for reporting.
The second dialogue was titled as 'Find a city' as it is used also for the temporary city action

**Comment by pmattern** [comment]
Commit 5284a59, which btw. is working as expected here, made me realize that 5cc08e9 is adding a superfluous ampersand to the German translation in line 79 of `meteo_qt.py`. Fixed in Transifex. But IIRC it was me who made this translation and I'm now wondering why the heck I should have introduced an additional character that exists neither in the template nor at first glance in any other translation.
Is there a way to figure out whether this was in fact some translator's mistake or whether this possibly reflects some technical problem?

**Comment by dglent** [comment]
Can you point me to the exact line in the file meteo_qt.py? 
In the line 79 now there is this: https://github.com/dglent/meteo-qt/blob/master/meteo_qt/meteo_qt.py#L79

**Comment by pmattern** [comment]
Apparently `meteo_qt.py` and `meteo-qt_de.ts` aren't exactly in sync? Anyway the relevant section in the latter is https://github.com/dglent/meteo-qt/blob/5284a599475fe2da7c1c70b875598f7f751c00e3/meteo_qt/translations/meteo-qt_de.ts#L719-L721.

**Comment by dglent** [comment]
No normally there was never a "&" there and the pylupdate shouldn't create one.
Nevertheless i'm wondering if it would be useful to add one ...

**Comment by pmattern** [comment]
> Nevertheless i'm wondering if it would be useful to add one ...

Normally ampersands are used to mark mnemonics, but if I'm not mistaken this string is meant to be used in title bars of dialogue windows only. So I don't think it would make sense here.

Anyway probably that strange ampersand in German was some copy-and-paste and/or fat fingers issue and I guess we shouldn't care any more as long as something similar doesn't crop up another time.

**Comment by dglent** [comment]
Actually the ampersand is used to create a shortcut in order to use the menu entries by the keyboard, but i don't think that this useful here as the mouse is the usual pointer device for this program (and after you will choose the city with the mouse ...) 
http://doc.qt.io/qt-5/qmenubar.html#details

**Comment by pmattern** [comment]
I wouldn't even say that pointer devices are the only relevant input device to handle meteo-qt. E. g. I for one find the mnemonics in the right column of dialogue "Cities", move up/down and so on, pretty convenient at times.
But again, if I'm not mistaken the particular string we're discussing here will never appear in a context where it may have to be chosen by keyboard, so an ampersand doesn't make sense.
