### ISSUE TITLE
More info

### ISSUE THREAD

**Issue by invexx** [dglent/meteo-qt#68]
It's only my opinion but I think it would be very useful  if windchill factor temperature would be displayed.
Especially for us living in a cold climate :)

And if under Sunset the daylight length (Sunset minus Sunrise) would be too.

If icon and temperature is displayed the temperature is quite small. Making it bold would make it more visible.

Overall it's a very nice program, though.

**Comment by dglent** [comment]
Hello,

I like these options, i will check them with the first occasion.
