### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by invexx** [dglent/meteo-qt#69]
It would be very useful if there was an option to disable tooltips.
They look nice in Unity. Not so in Mint.

**Comment by dglent** [comment]
Could you post a screenshot ?

**Comment by invexx** [comment]
Sure.
![selection_581](https://cloud.githubusercontent.com/assets/26446962/24376937/d5235ad4-12fa-11e7-85b8-731d9f140b64.png)

**Comment by dglent** [comment]
This you can disable it by the settings. You have it one time only when you change the city.

**Comment by invexx** [comment]
Damn! I don't understand how I could overlook it :) Sorry about that
