### ISSUE TITLE
On dark panel, tray icon temperature is wrong display

### ISSUE THREAD

**Issue by rcspam** [dglent/meteo-qt#72]
Hi
On dark panel, tray icon temperature is wrong display (i'm on ubuntu 16.04): fonts are dark on dark.
Best regards

**Comment by dglent** [comment]
Hello,

Did you try to change the font color from the settings ?

**Comment by rcspam** [comment]
Hi Dimitros, I have to update the same color to make color font works,
thanks.. Apparently the first start doesn't update font... Perhaps a bug
Thanks
Regards


2017-04-13 15:11 GMT+02:00 Dimitrios Glentadakis <notifications@github.com>:
