### ISSUE TITLE
Change wind speed unit to kph or knots

### ISSUE THREAD

**Issue by nettlebay** [dglent/meteo-qt#74]
It's a shame that it's not possible to change wind speed units from m/s to km/h (kph) or even knots. Meters/second are not intuitive... Is there a trick?

**Comment by dglent** [comment]
What about Beaufort ? 

![details7](https://cloud.githubusercontent.com/assets/4337756/25561406/37e193b8-2d6b-11e7-9d54-770f93455ce9.png)
img>

**Comment by nettlebay** [comment]
Hello!
"Wind Unit in Beaufort" is not visible in mine. Snapshot:
http://i.imgur.com/HPVMJF8.png

**Comment by dglent** [comment]
It is not released yet. This option was included last month in git bersion
https://github.com/dglent/meteo-qt/commit/f59d66570f61c44ede904d47f3d2b196429882e7

**Comment by dglent** [comment]
Option to set the wind speed in km/h
https://github.com/dglent/meteo-qt/commit/c6c3c3647e96789b47244819b1486bb42ae53217
