### ISSUE TITLE
Pressure and/or temperature trend symbol not showing

### ISSUE THREAD

**Issue by jose1711** [dglent/meteo-qt#85]
![obrázok](https://user-images.githubusercontent.com/1406222/58018965-95833380-7b04-11e9-8a7d-0453cf976619.png)
there should be a symbol showing whether barometric pressure is rising or falling. but on my two arch linux systems (i3 and gnome) i either get an empty box (above) or underscore character.

i can see that symbols are defined as UTF-8 symbol from private area. i think using common arrow characters such as ↗, ↘ or → would be more appropriate. the same is true for temperature trend.

**Comment by dglent** [comment]
Hello

Thanks for all commits

Actually i have a problem with my personal pc
I will check this a little later

**Comment by dglent** [comment]
Hello 

could you test the above commit ? (for the hpa too https://github.com/dglent/meteo-qt/commit/6dc4139b70c371fd18143e457742c2f9217a8e1f)

**Comment by jose1711** [comment]
works nicely. thank you for the fix!
