### ISSUE TITLE
Binary packages for debian and ubuntu

### ISSUE THREAD

**Issue by agaida** [dglent/meteo-qt#89]
Maybe it's about time to mention that meteo-qt is in the official Debian repositories - nearly the same for Ubuntu :

https://tracker.debian.org/pkg/meteo-qt  
https://packages.ubuntu.com/source/eoan/meteo-qt  

In general: https://pkgs.org/download/meteo-qt   

Maybe worth a mention - btw, just uploaded 1.3 to sid, great work, thanks.

**Comment by dglent** [comment]
Hello

Thanks a lot for the packages!
* Note that the versions before 1.3 don't work any more due some changes on the received weather data.

**Comment by agaida** [comment]
Noticed - but there is a problem: i can't introduce meteo-qt 1.3 into the just released debian buster - the only way right now i see are backports - porting back the needed things for the config changes seems to me like a big waste of time - any ideas?
