### ISSUE TITLE
meteo-gtk does not require api why meteo-qt requires it?

### ISSUE THREAD

**Issue by librewish** [dglent/meteo-qt#92]
https://aur.archlinux.org/packages/meteo-gtk

this aur package does not require to enter the api key to use the app

while meteo-qt requires

both are meteo

**Comment by dglent** [comment]
Hello
Initially, i provided a common key but it has been [hijacked](https://openweathermap.desk.com/customer/en/portal/questions/16336038-my-application-stopped-worked-because-of-over-usage) and the application didn't work any more.
