### ISSUE TITLE
meteo-qt stopped updating (roughly Dec 12, 2019)

### ISSUE THREAD

**Issue by notbeep** [dglent/meteo-qt#94]
When I run it manually in terminal, I get a bunch of:
```
ERROR: 6 days forcast not available : HTTP Error 401: Unauthorized - 1858 :meteo_qt
WARNING: Error: can only concatenate str (not "NoneType") to str - 1934 :meteo_qt
INFO: Try again...1 - 1935 :meteo_qt
ERROR: 6 days forcast not available : HTTP Error 401: Unauthorized - 1858 :meteo_qt
WARNING: Error: can only concatenate str (not "NoneType") to str - 1934 :meteo_qt
INFO: Try again...2 - 1935 :meteo_qt
```
Then I tried creating a new OWM API key, figuring it was maybe that, and get:
```
ERROR: 6 days forcast not available : HTTP Error 401: Unauthorized - 1858 :meteo_qt
WARNING: Error: HTTP Error 401: Unauthorized - 1934 :meteo_qt
INFO: Try again...1 - 1935 :meteo_qt
ERROR: 6 days forcast not available : HTTP Error 401: Unauthorized - 1858 :meteo_qt
WARNING: Error: HTTP Error 401: Unauthorized - 1934 :meteo_qt
INFO: Try again...2 - 1935 :meteo_qt

$ sudo apt install meteo-qt
meteo-qt is already the newest version (1.0.0-1).
```
I also tried this in meteo-qt version 1.3, and get the same issue.
```
$ cat /etc/os-release 
NAME="Ubuntu" 
VERSION="19.04 (Disco Dingo)"
```
I went into the API calls, and it was calling a URL like this:
http://api.openweathermap.org/data/2.5/forecast/daily?

and getting a result:
```
{"cod":401, "message": "Invalid API key. Please see http://openweathermap.org/faq#error401 for more info."}
```
But I changed the URL to something like this (removing the word daily, but keeping the APIKEY the same):
http://api.openweathermap.org/data/2.5/forecast?

And now I get valid results. So I think maybe OWM changed their API?

**Comment by dglent** [comment]
Could you check with thé Last commit?
https://github.com/dglent/meteo-qt/commit/117a56095dbdf424d43ae3da19c9bd3efcb72d0a

**Comment by kovtunos** [comment]
The last commit works for me.

**Comment by notbeep** [comment]
Running from the latest commit, everything loads and I get my temperature/icon in the tray, but I still this output in the log:

$ python3 meteo_qt/meteo_qt.py 
Icon theme "breeze" not found.
DEBUG: Update... - 1434: meteo_qt
DEBUG: Fetching url for 6 days: http://api.openweathermap.org/data/2.5/forecast/daily?id=ID&mode=xml&units=imperial&APPID=APIKEY&cnt=7 - 1981: meteo_qt
ERROR: Url of 6 days forcast not available: http://api.openweathermap.org/data/2.5/forecast/daily?id=ID&mode=xml&units=imperial&APPID=APIKEY&cnt=7 - 2005: meteo_qt
ERROR: 6 days forcast not available: HTTP Error 401: Unauthorized - 2006: meteo_qt
DEBUG: Fetching url for actual weather: http://api.openweathermap.org/data/2.5/weather?id=ID&mode=xml&units=imperial&APPID=APIKEY - 2011: meteo_qt
DEBUG: Fetching url for forecast of the day + 4:http://api.openweathermap.org/data/2.5/forecast?id=ID&mode=xml&units=imperial&APPID=APIKEY - 2017: meteo_qt
Traceback (most recent call last):
  File "meteo_qt/meteo_qt.py", line 2053, in run
    raise TypeError
TypeError
DEBUG: Error, use JSON page for the actual weather infoNone - 2057: meteo_qt
DEBUG: Icon url: http://openweathermap.org/img/w/02d.png - 2075: meteo_qt
DEBUG: Download thread done - 2126: meteo_qt
DEBUG: Wind degrees direction: 355 - 574: meteo_qt
2019/12/15 13:06:34 CRASH:
--------------------------------------------------------------------------------
<class 'TypeError'>      
can only concatenate str (not "NoneType") to str
--------------------------------------------------------------------------------
  File "meteo_qt/meteo_qt.py", line 1479, in done
    self.overviewcity()
  File "meteo_qt/meteo_qt.py", line 443, in overviewcity
    self.forecastdata()
  File "meteo_qt/meteo_qt.py", line 942, in forecastdata
    weather_cond += '\n' + clouds_label + clouds + ' %'

DEBUG: Paint tray icon... - 1711: meteo_qt
INFO: Actual weather status for:  City US 55.0° few clouds - 1763: meteo_qt

**Comment by dglent** [comment]
You reproduce it always ?
Can you give me a city which you reproduce this output ?

**Comment by notbeep** [comment]
Yes the log output I pasted is still showing up in the latest 1.4 commit today Dec 16, but now everything's working (weather is updating, tray icon is showing, etc). In 1.3 and 1.0 it was not updating as of Dec 12 or so. Screenshot of config attached.

![meteoqt](https://user-images.githubusercontent.com/58862803/70935302-be18d080-1ff4-11ea-8034-758cf1b37ad0.jpg)

**Comment by RafaGamas** [comment]
I can't update the weather info from the same date (around 12 or 13 December). The tray icon is always in the loading status, and if I pass the mouse over displays "Fetching weather data..."

**Comment by dglent** [comment]
I 'm about to fix this
Actually i was n't aware, they have added the Feels Like temperature and the data tree is broken
So, i will add the Feels Like temperature on the window and fix the broken values

**Comment by notbeep** [comment]
Also the link on the main github page https://github.com/dglent/meteo-qt for Ubuntu packages is dead ( http://www.getdeb.net/app/meteo-qt )

**Comment by notbeep** [comment]
Error seems to be gone with new commit.

**Comment by dglent** [comment]
Ok the problem with the data was fixed
The 'Feels like' T° was added in the weather info panel, in the forecast of the day and for the next days tooltips and on the notification tooltip of the systemtray icon
