### ISSUE TITLE
feature: request option for feels.like.temp in tray instead of raw temp

### ISSUE THREAD

**Issue by notbeep** [dglent/meteo-qt#95]
In the tray icon, right now the temperature is showing, and it would be great to instead have an option for the feels.like, or maybe just to make that the default since it seems a better gauge now that the API has it available, than the raw temp.
![screenshot feelslike](https://user-images.githubusercontent.com/58862803/71312930-4aa50380-23e6-11ea-93af-147c1b70521f.jpg)

**Comment by dglent** [comment]
Good idea, thanks
Check the above commit please

**Comment by notbeep** [comment]
Works great, now have the option for feels-like+icon and feels-like, thanks so much!
