### ISSUE TITLE
Better support for 4K display

### ISSUE THREAD

**Issue by fabrixx** [dglent/meteo-qt#97]
i've a monitor 4K, tryed various font size and colour but is difficult to read the temperature because remain under icon that is very tiny

**Comment by dglent** [comment]
If you change the taskbar size makes  difference ?
Can you show a screenshot ?

**Comment by fabrixx** [comment]
It is a particular 15 inch 4k monitor, I can put the screenshot later. This is the taskbar of gnome 3.36. If I enlarge the half number character it remains beyond the upper margin and even changing the color it mixes with the icon graphics. Now i'm with 4k 24 inch. I have seen, however, that only the number can be displayed. In this monitor the icon is always too small but if I enlarge it, the number is only slightly cut on the round of the degrees. 
![b](https://user-images.githubusercontent.com/1190942/77688405-546b7380-6fa0-11ea-8e30-cb8ca53b007d.png)
![a](https://user-images.githubusercontent.com/1190942/77688410-559ca080-6fa0-11ea-9c60-8360e8456874.png)

**Comment by dglent** [comment]
Did you try to adjust the T° font size from the meteo-qt settings?

An option to toggle icon and T° every a defined interval (seconds) would help ?
To avoid to have the icon and the T° together.

**Comment by dglent** [comment]
I have added an option to toggle the tray icon and temperature (or Feels Like T°), may be is convenient for your screen too:
https://github.com/dglent/meteo-qt/commit/99d0bcc178af411a8fd4db5abcec3abbd7c8f34b

**Comment by fabrixx** [comment]
Ok this time I didn't use Arch's meteo-qt-git package but I installed directly from the sources.

The alternation function is interesting but the icon is really too small on my 4K monitor.

Increasing the font size the first digit is cut to the left so I can't zoom in much. If I set it to 21 I get a good compromise, then I copied the gray color of the bar.

Thanks for the work you do.

My desktop hires large images:
https://imgur.com/a/TvLTihc

**Comment by dglent** [comment]
I see
It cannot be bigger as it reaches the maximum dimensions of an icon.
Only the widgets can be bigger.
I don't know what Desktop you use, maybe you have an option to set the icons size of the taskbar
In LXQt fort example you have this option.

**Comment by dglent** [comment]
Font dialog to set the font of the T° in the system tray https://github.com/dglent/meteo-qt/commit/5d528e2f40c1ad5550b405a81a0d309a9f84b90e
