### ISSUE TITLE
Fedora 32 beta, meteo window no contents

### ISSUE THREAD

**Issue by coz** [dglent/meteo-qt#98]
I am using Fedora 32 beta. I expect a few bugs with the system. Meteo installs  but the result is a  nearly blank window
![Screenshot at 2020-03-30 02-56-20](https://user-images.githubusercontent.com/907664/77883946-1c7b5f00-7232-11ea-99a4-fa461a24046d.png)

**Comment by dglent** [comment]
Hello
I don't recognise this window.
The meteo-qt window should look like this : https://github.com/dglent/meteo-qt/issues/96#issuecomment-598329721
It isn't another application ?
Try to run meteo-qt in the terminal

**Comment by dglent** [comment]
Ping ?

**Comment by jose1711** [comment]
This is a misguided bugreport. For Meteo issues head to https://gitlab.com/bitseater/meteo. @dglent Please close as invalid.
